// Code generated by apigen from backend/openapi.json. DO NOT EDIT.

package suppuo

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
)

// apigenTransport is the call behind every GeneratedAPI method: the SDK client sends it
// with its own sign-in and unwraps its own response envelope (a few hand-written lines
// in the client, apigenRequest). query is nil or the query string; body is nil (no body)
// or the JSON body. It returns the envelope's data, as JSON.
type apigenTransport interface {
	apigenRequest(ctx context.Context, method, path string, query url.Values, body map[string]any) (json.RawMessage, error)
}

// GeneratedAPI has all 67 feature routes of the Suppuo API, one method each
// (generated from the API spec). A method takes the path parameters, then an *<Method>Args
// with the query fields (tagged query) and the JSON body fields (tagged json): required
// fields are plain values, optional ones pointers, slices or maps that nil leaves out,
// and Body passes the whole body. Each returns the response's data as JSON.
type GeneratedAPI struct{ c apigenTransport }

// Ptr returns a pointer to v, for the optional fields of the *Args structs.
func Ptr[T any](v T) *T { return &v }

// APIKeysCreateArgs are the inputs of GeneratedAPI.APIKeysCreate.
type APIKeysCreateArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// APIKeysCreate calls POST /api/v1/api-keys: Create an api key.
func (a *GeneratedAPI) APIKeysCreate(ctx context.Context, p *APIKeysCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &APIKeysCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("APIKeysCreate", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/api-keys", nil, payload)
}

// APIKeysDelete calls DELETE /api/v1/api-keys/{id}: Delete an api key.
func (a *GeneratedAPI) APIKeysDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/api-keys/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// APIKeysList calls GET /api/v1/api-keys: List api keys.
func (a *GeneratedAPI) APIKeysList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/api-keys", nil, nil)
}

// AttachmentsCreateArgs are the inputs of GeneratedAPI.AttachmentsCreate.
type AttachmentsCreateArgs struct {
	// Length is "length" in the body.
	Length any `json:"length,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AttachmentsCreate calls POST /api/v1/attachments: Create an attachment.
func (a *GeneratedAPI) AttachmentsCreate(ctx context.Context, p *AttachmentsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AttachmentsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Length != nil {
		payload["length"] = p.Length
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/attachments", nil, payload)
}

// AttachmentsGet calls GET /api/v1/attachments/{id}: Get an attachment.
func (a *GeneratedAPI) AttachmentsGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/attachments/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// BillingCheckoutArgs are the inputs of GeneratedAPI.BillingCheckout.
type BillingCheckoutArgs struct {
	// Tier is "tier" in the body, required. One of: free, starter, growth, business.
	Tier string `json:"tier"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// BillingCheckout calls POST /api/v1/billing/checkout: POST /checkout {tier} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl.
func (a *GeneratedAPI) BillingCheckout(ctx context.Context, p *BillingCheckoutArgs) (json.RawMessage, error) {
	if p == nil {
		p = &BillingCheckoutArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Tier != "" {
		payload["tier"] = p.Tier
	}
	if _, ok := payload["tier"]; !ok {
		return nil, apigenMissing("BillingCheckout", "Tier")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/billing/checkout", nil, payload)
}

// BillingList calls GET /api/v1/billing: Current subscription (free default when no row) + the tier table the portal renders.
func (a *GeneratedAPI) BillingList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/billing", nil, nil)
}

// CannedRepliesCreateArgs are the inputs of GeneratedAPI.CannedRepliesCreate.
type CannedRepliesCreateArgs struct {
	// Title is "title" in the body, required.
	Title string `json:"title"`

	// BodyField is "body" in the body, required.
	BodyField string `json:"body"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// CannedRepliesCreate calls POST /api/v1/canned-replies: Create a canned reply.
func (a *GeneratedAPI) CannedRepliesCreate(ctx context.Context, p *CannedRepliesCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &CannedRepliesCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Title != "" {
		payload["title"] = p.Title
	}
	if p.BodyField != "" {
		payload["body"] = p.BodyField
	}
	if _, ok := payload["title"]; !ok {
		return nil, apigenMissing("CannedRepliesCreate", "Title")
	}
	if _, ok := payload["body"]; !ok {
		return nil, apigenMissing("CannedRepliesCreate", "BodyField")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/canned-replies", nil, payload)
}

// CannedRepliesDelete calls DELETE /api/v1/canned-replies/{id}: Delete a canned reply.
func (a *GeneratedAPI) CannedRepliesDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/canned-replies/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// CannedRepliesList calls GET /api/v1/canned-replies: List canned replies.
func (a *GeneratedAPI) CannedRepliesList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/canned-replies", nil, nil)
}

// CannedRepliesUpdateArgs are the inputs of GeneratedAPI.CannedRepliesUpdate.
type CannedRepliesUpdateArgs struct {
	// Title is "title" in the body.
	Title *string `json:"title,omitempty"`

	// BodyField is "body" in the body.
	BodyField *string `json:"body,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// CannedRepliesUpdate calls PATCH /api/v1/canned-replies/{id}: Update a canned reply.
func (a *GeneratedAPI) CannedRepliesUpdate(ctx context.Context, id string, p *CannedRepliesUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &CannedRepliesUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Title != nil {
		payload["title"] = *p.Title
	}
	if p.BodyField != nil {
		payload["body"] = *p.BodyField
	}
	path := "/api/v1/canned-replies/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ChannelsCreateArgs are the inputs of GeneratedAPI.ChannelsCreate.
type ChannelsCreateArgs struct {
	// Provider is "provider" in the body. One of: whatsapp_twilio, whatsapp_cloud, email_resend, telegram_bot, slack_webhook, discord_webhook.
	Provider *string `json:"provider,omitempty"`

	// AccountSid is "accountSid" in the body.
	AccountSid *string `json:"accountSid,omitempty"`

	// AuthToken is "authToken" in the body.
	AuthToken *string `json:"authToken,omitempty"`

	// WhatsappNumber is "whatsappNumber" in the body.
	WhatsappNumber *string `json:"whatsappNumber,omitempty"`

	// DisplayName is "displayName" in the body.
	DisplayName *string `json:"displayName,omitempty"`

	// AccessToken is "accessToken" in the body.
	AccessToken *string `json:"accessToken,omitempty"`

	// PhoneNumberID is "phoneNumberId" in the body.
	PhoneNumberID *string `json:"phoneNumberId,omitempty"`

	// WabaID is "wabaId" in the body.
	WabaID *string `json:"wabaId,omitempty"`

	// DisplayNumber is "displayNumber" in the body.
	DisplayNumber *string `json:"displayNumber,omitempty"`

	// VerifyToken is "verifyToken" in the body.
	VerifyToken *string `json:"verifyToken,omitempty"`

	// AppSecret is "appSecret" in the body.
	AppSecret *string `json:"appSecret,omitempty"`

	// APIKey is "apiKey" in the body.
	APIKey *string `json:"apiKey,omitempty"`

	// FromEmail is "fromEmail" in the body.
	FromEmail *string `json:"fromEmail,omitempty"`

	// FromName is "fromName" in the body.
	FromName *string `json:"fromName,omitempty"`

	// BotToken is "botToken" in the body.
	BotToken *string `json:"botToken,omitempty"`

	// WebhookURL is "webhookUrl" in the body.
	WebhookURL *string `json:"webhookUrl,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ChannelsCreate calls POST /api/v1/channels: Create a channel.
func (a *GeneratedAPI) ChannelsCreate(ctx context.Context, p *ChannelsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ChannelsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Provider != nil {
		payload["provider"] = *p.Provider
	}
	if p.AccountSid != nil {
		payload["accountSid"] = *p.AccountSid
	}
	if p.AuthToken != nil {
		payload["authToken"] = *p.AuthToken
	}
	if p.WhatsappNumber != nil {
		payload["whatsappNumber"] = *p.WhatsappNumber
	}
	if p.DisplayName != nil {
		payload["displayName"] = *p.DisplayName
	}
	if p.AccessToken != nil {
		payload["accessToken"] = *p.AccessToken
	}
	if p.PhoneNumberID != nil {
		payload["phoneNumberId"] = *p.PhoneNumberID
	}
	if p.WabaID != nil {
		payload["wabaId"] = *p.WabaID
	}
	if p.DisplayNumber != nil {
		payload["displayNumber"] = *p.DisplayNumber
	}
	if p.VerifyToken != nil {
		payload["verifyToken"] = *p.VerifyToken
	}
	if p.AppSecret != nil {
		payload["appSecret"] = *p.AppSecret
	}
	if p.APIKey != nil {
		payload["apiKey"] = *p.APIKey
	}
	if p.FromEmail != nil {
		payload["fromEmail"] = *p.FromEmail
	}
	if p.FromName != nil {
		payload["fromName"] = *p.FromName
	}
	if p.BotToken != nil {
		payload["botToken"] = *p.BotToken
	}
	if p.WebhookURL != nil {
		payload["webhookUrl"] = *p.WebhookURL
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/channels", nil, payload)
}

// ChannelsDelete calls DELETE /api/v1/channels/{id}: Delete a channel.
func (a *GeneratedAPI) ChannelsDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/channels/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// ChannelsList calls GET /api/v1/channels: List channels.
func (a *GeneratedAPI) ChannelsList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/channels", nil, nil)
}

// CsatStats calls GET /api/v1/csat/stats: List stats.
func (a *GeneratedAPI) CsatStats(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/csat/stats", nil, nil)
}

// DomainsCreateArgs are the inputs of GeneratedAPI.DomainsCreate.
type DomainsCreateArgs struct {
	// Domain is "domain" in the body, required.
	Domain string `json:"domain"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// DomainsCreate calls POST /api/v1/domains: Create a domain.
func (a *GeneratedAPI) DomainsCreate(ctx context.Context, p *DomainsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &DomainsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Domain != "" {
		payload["domain"] = p.Domain
	}
	if _, ok := payload["domain"]; !ok {
		return nil, apigenMissing("DomainsCreate", "Domain")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/domains", nil, payload)
}

// DomainsDelete calls DELETE /api/v1/domains/{id}: Delete a domain.
func (a *GeneratedAPI) DomainsDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/domains/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// DomainsList calls GET /api/v1/domains: List domains.
func (a *GeneratedAPI) DomainsList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/domains", nil, nil)
}

// DomainsVerify calls POST /api/v1/domains/{id}/verify: Verify a domain.
func (a *GeneratedAPI) DomainsVerify(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/domains/" + url.PathEscape(id) + "/verify"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// HelpArticles calls GET /api/v1/help/articles: List articles.
func (a *GeneratedAPI) HelpArticles(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/help/articles", nil, nil)
}

// HelpArticles2 calls GET /api/v1/help/articles/{id}: Get an article.
func (a *GeneratedAPI) HelpArticles2(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/help/articles/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// HelpCreateArticlesArgs are the inputs of GeneratedAPI.HelpCreateArticles.
type HelpCreateArticlesArgs struct {
	// Kind is "kind" in the body. One of: faq, article.
	Kind *string `json:"kind,omitempty"`

	// Slug is "slug" in the body.
	Slug *string `json:"slug,omitempty"`

	// Category is "category" in the body.
	Category *string `json:"category,omitempty"`

	// Title is "title" in the body, required.
	Title string `json:"title"`

	// BodyField is "body" in the body, required.
	BodyField string `json:"body"`

	// Status is "status" in the body. One of: draft, published.
	Status *string `json:"status,omitempty"`

	// Position is "position" in the body.
	Position *int `json:"position,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// HelpCreateArticles calls POST /api/v1/help/articles: Create an article.
func (a *GeneratedAPI) HelpCreateArticles(ctx context.Context, p *HelpCreateArticlesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &HelpCreateArticlesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Kind != nil {
		payload["kind"] = *p.Kind
	}
	if p.Slug != nil {
		payload["slug"] = *p.Slug
	}
	if p.Category != nil {
		payload["category"] = *p.Category
	}
	if p.Title != "" {
		payload["title"] = p.Title
	}
	if p.BodyField != "" {
		payload["body"] = p.BodyField
	}
	if p.Status != nil {
		payload["status"] = *p.Status
	}
	if p.Position != nil {
		payload["position"] = *p.Position
	}
	if _, ok := payload["title"]; !ok {
		return nil, apigenMissing("HelpCreateArticles", "Title")
	}
	if _, ok := payload["body"]; !ok {
		return nil, apigenMissing("HelpCreateArticles", "BodyField")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/help/articles", nil, payload)
}

// HelpDeleteArticles calls DELETE /api/v1/help/articles/{id}: Delete an article.
func (a *GeneratedAPI) HelpDeleteArticles(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/help/articles/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// HelpUpdateArticlesArgs are the inputs of GeneratedAPI.HelpUpdateArticles.
type HelpUpdateArticlesArgs struct {
	// Kind is "kind" in the body. One of: faq, article.
	Kind *string `json:"kind,omitempty"`

	// Slug is "slug" in the body.
	Slug *string `json:"slug,omitempty"`

	// Category is "category" in the body.
	Category *string `json:"category,omitempty"`

	// Title is "title" in the body.
	Title *string `json:"title,omitempty"`

	// BodyField is "body" in the body.
	BodyField *string `json:"body,omitempty"`

	// Status is "status" in the body. One of: draft, published.
	Status *string `json:"status,omitempty"`

	// Position is "position" in the body.
	Position *int `json:"position,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// HelpUpdateArticles calls PATCH /api/v1/help/articles/{id}: Update an article.
func (a *GeneratedAPI) HelpUpdateArticles(ctx context.Context, id string, p *HelpUpdateArticlesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &HelpUpdateArticlesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Kind != nil {
		payload["kind"] = *p.Kind
	}
	if p.Slug != nil {
		payload["slug"] = *p.Slug
	}
	if p.Category != nil {
		payload["category"] = *p.Category
	}
	if p.Title != nil {
		payload["title"] = *p.Title
	}
	if p.BodyField != nil {
		payload["body"] = *p.BodyField
	}
	if p.Status != nil {
		payload["status"] = *p.Status
	}
	if p.Position != nil {
		payload["position"] = *p.Position
	}
	path := "/api/v1/help/articles/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// MeList calls GET /api/v1/me: List me.
func (a *GeneratedAPI) MeList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/me", nil, nil)
}

// ProfileAvatar calls GET /api/v1/profile/avatar/{sub}: Get an avatar.
func (a *GeneratedAPI) ProfileAvatar(ctx context.Context, sub string) (json.RawMessage, error) {
	path := "/api/v1/profile/avatar/" + url.PathEscape(sub)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProfileDeleteAvatar calls DELETE /api/v1/profile/avatar: Delete avatar.
func (a *GeneratedAPI) ProfileDeleteAvatar(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "DELETE", "/api/v1/profile/avatar", nil, nil)
}

// ProfileSetAvatarArgs are the inputs of GeneratedAPI.ProfileSetAvatar.
type ProfileSetAvatarArgs struct {
	// Length is "length" in the body.
	Length any `json:"length,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProfileSetAvatar calls PUT /api/v1/profile/avatar: Set avatar.
func (a *GeneratedAPI) ProfileSetAvatar(ctx context.Context, p *ProfileSetAvatarArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProfileSetAvatarArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Length != nil {
		payload["length"] = p.Length
	}
	return a.c.apigenRequest(ctx, "PUT", "/api/v1/profile/avatar", nil, payload)
}

// PublicCreateTicketsArgs are the inputs of GeneratedAPI.PublicCreateTickets.
type PublicCreateTicketsArgs struct {
	// AccountID is "accountId" in the body, required.
	AccountID string `json:"accountId"`

	// Subject is "subject" in the body, required.
	Subject string `json:"subject"`

	// BodyField is "body" in the body, required.
	BodyField string `json:"body"`

	// Email is "email" in the body, required.
	Email string `json:"email"`

	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// Company is "company" in the body.
	Company *string `json:"company,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// PublicCreateTickets calls POST /api/v1/public/tickets: Create a ticket.
func (a *GeneratedAPI) PublicCreateTickets(ctx context.Context, p *PublicCreateTicketsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicCreateTicketsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.AccountID != "" {
		payload["accountId"] = p.AccountID
	}
	if p.Subject != "" {
		payload["subject"] = p.Subject
	}
	if p.BodyField != "" {
		payload["body"] = p.BodyField
	}
	if p.Email != "" {
		payload["email"] = p.Email
	}
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.Company != nil {
		payload["company"] = *p.Company
	}
	if _, ok := payload["accountId"]; !ok {
		return nil, apigenMissing("PublicCreateTickets", "AccountID")
	}
	if _, ok := payload["subject"]; !ok {
		return nil, apigenMissing("PublicCreateTickets", "Subject")
	}
	if _, ok := payload["body"]; !ok {
		return nil, apigenMissing("PublicCreateTickets", "BodyField")
	}
	if _, ok := payload["email"]; !ok {
		return nil, apigenMissing("PublicCreateTickets", "Email")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/public/tickets", nil, payload)
}

// PublicCreateTicketsAttachmentsArgs are the inputs of GeneratedAPI.PublicCreateTicketsAttachments.
type PublicCreateTicketsAttachmentsArgs struct {
	// Length is "length" in the body.
	Length any `json:"length,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// PublicCreateTicketsAttachments calls POST /api/v1/public/tickets/{accessToken}/attachments: Attachments a ticket.
func (a *GeneratedAPI) PublicCreateTicketsAttachments(ctx context.Context, accessToken string, p *PublicCreateTicketsAttachmentsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicCreateTicketsAttachmentsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Length != nil {
		payload["length"] = p.Length
	}
	path := "/api/v1/public/tickets/" + url.PathEscape(accessToken) + "/attachments"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// PublicDomainsProvisionCallbackArgs are the inputs of GeneratedAPI.PublicDomainsProvisionCallback.
type PublicDomainsProvisionCallbackArgs struct {
	// Domain is "domain" in the body, required.
	Domain string `json:"domain"`

	// Status is "status" in the body, required. One of: success, failed.
	Status string `json:"status"`

	// Error is "error" in the body.
	Error *string `json:"error,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// PublicDomainsProvisionCallback calls POST /api/v1/public/domains/provision-callback: Create a provision callback.
func (a *GeneratedAPI) PublicDomainsProvisionCallback(ctx context.Context, p *PublicDomainsProvisionCallbackArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicDomainsProvisionCallbackArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Domain != "" {
		payload["domain"] = p.Domain
	}
	if p.Status != "" {
		payload["status"] = p.Status
	}
	if p.Error != nil {
		payload["error"] = *p.Error
	}
	if _, ok := payload["domain"]; !ok {
		return nil, apigenMissing("PublicDomainsProvisionCallback", "Domain")
	}
	if _, ok := payload["status"]; !ok {
		return nil, apigenMissing("PublicDomainsProvisionCallback", "Status")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/public/domains/provision-callback", nil, payload)
}

// PublicDomainsResolveArgs are the inputs of GeneratedAPI.PublicDomainsResolve.
type PublicDomainsResolveArgs struct {
	// Host is "host" in the query.
	Host any `query:"host"`
}

// PublicDomainsResolve calls GET /api/v1/public/domains/resolve: Host → accountId — used by the frontend middleware to route a custom domain's request to the right workspace.
func (a *GeneratedAPI) PublicDomainsResolve(ctx context.Context, p *PublicDomainsResolveArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicDomainsResolveArgs{}
	}
	q := url.Values{}
	if p.Host != nil {
		q.Set("host", apigenQueryValue(p.Host))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/public/domains/resolve", q, nil)
}

// PublicHelp calls GET /api/v1/public/help/{accountId}: The help-center bundle.
func (a *GeneratedAPI) PublicHelp(ctx context.Context, accountID string) (json.RawMessage, error) {
	path := "/api/v1/public/help/" + url.PathEscape(accountID)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// PublicHelpA calls GET /api/v1/public/help/{accountId}/a/{slug}: A single published article.
func (a *GeneratedAPI) PublicHelpA(ctx context.Context, accountID string, slug string) (json.RawMessage, error) {
	path := "/api/v1/public/help/" + url.PathEscape(accountID) + "/a/" + url.PathEscape(slug)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// PublicHelpBranding calls GET /api/v1/public/help/{accountId}/branding: Public branding (logo + colors + name) for the help center AND the hosted portal's pre-auth screen.
func (a *GeneratedAPI) PublicHelpBranding(ctx context.Context, accountID string) (json.RawMessage, error) {
	path := "/api/v1/public/help/" + url.PathEscape(accountID) + "/branding"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// PublicHelpLogo calls GET /api/v1/public/help/{accountId}/logo: Serve the uploaded brand logo bytes.
func (a *GeneratedAPI) PublicHelpLogo(ctx context.Context, accountID string) (json.RawMessage, error) {
	path := "/api/v1/public/help/" + url.PathEscape(accountID) + "/logo"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// PublicHelpSearchArgs are the inputs of GeneratedAPI.PublicHelpSearch.
type PublicHelpSearchArgs struct {
	// Q is "q" in the query.
	Q *string `query:"q"`
}

// PublicHelpSearch calls GET /api/v1/public/help/{accountId}/search: List search.
func (a *GeneratedAPI) PublicHelpSearch(ctx context.Context, accountID string, p *PublicHelpSearchArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicHelpSearchArgs{}
	}
	q := url.Values{}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(*p.Q))
	}
	path := "/api/v1/public/help/" + url.PathEscape(accountID) + "/search"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// PublicRequesterVerifyArgs are the inputs of GeneratedAPI.PublicRequesterVerify.
type PublicRequesterVerifyArgs struct {
	// Token is "token" in the body, required.
	Token string `json:"token"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// PublicRequesterVerify calls POST /api/v1/public/requester/verify: Create a verify.
func (a *GeneratedAPI) PublicRequesterVerify(ctx context.Context, p *PublicRequesterVerifyArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicRequesterVerifyArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Token != "" {
		payload["token"] = p.Token
	}
	if _, ok := payload["token"]; !ok {
		return nil, apigenMissing("PublicRequesterVerify", "Token")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/public/requester/verify", nil, payload)
}

// PublicTickets calls GET /api/v1/public/tickets/{accessToken}: Tokenized status view — public messages only, no internal notes.
func (a *GeneratedAPI) PublicTickets(ctx context.Context, accessToken string) (json.RawMessage, error) {
	path := "/api/v1/public/tickets/" + url.PathEscape(accessToken)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// PublicTicketsAttachments calls GET /api/v1/public/tickets/{accessToken}/attachments/{id}: Get an attachment.
func (a *GeneratedAPI) PublicTicketsAttachments(ctx context.Context, accessToken string, id string) (json.RawMessage, error) {
	path := "/api/v1/public/tickets/" + url.PathEscape(accessToken) + "/attachments/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// PublicTicketsCsatArgs are the inputs of GeneratedAPI.PublicTicketsCsat.
type PublicTicketsCsatArgs struct {
	// Score is "score" in the body, required.
	Score int `json:"score"`

	// Comment is "comment" in the body.
	Comment *string `json:"comment,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// PublicTicketsCsat calls POST /api/v1/public/tickets/{accessToken}/csat: Csat a ticket.
func (a *GeneratedAPI) PublicTicketsCsat(ctx context.Context, accessToken string, p *PublicTicketsCsatArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicTicketsCsatArgs{}
	}
	payload := apigenBody(p.Body)
	if _, ok := payload["score"]; !ok || p.Score != 0 {
		payload["score"] = p.Score
	}
	if p.Comment != nil {
		payload["comment"] = *p.Comment
	}
	path := "/api/v1/public/tickets/" + url.PathEscape(accessToken) + "/csat"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// PublicTicketsMessagesArgs are the inputs of GeneratedAPI.PublicTicketsMessages.
type PublicTicketsMessagesArgs struct {
	// BodyField is "body" in the body, required.
	BodyField string `json:"body"`

	// AttachmentIDs is "attachmentIds" in the body.
	AttachmentIDs []string `json:"attachmentIds,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// PublicTicketsMessages calls POST /api/v1/public/tickets/{accessToken}/messages: Messages a ticket.
func (a *GeneratedAPI) PublicTicketsMessages(ctx context.Context, accessToken string, p *PublicTicketsMessagesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicTicketsMessagesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.BodyField != "" {
		payload["body"] = p.BodyField
	}
	if p.AttachmentIDs != nil {
		payload["attachmentIds"] = p.AttachmentIDs
	}
	if _, ok := payload["body"]; !ok {
		return nil, apigenMissing("PublicTicketsMessages", "BodyField")
	}
	path := "/api/v1/public/tickets/" + url.PathEscape(accessToken) + "/messages"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// PublicWidgetConfigArgs are the inputs of GeneratedAPI.PublicWidgetConfig.
type PublicWidgetConfigArgs struct {
	// Account is "account" in the query.
	Account any `query:"account"`
}

// PublicWidgetConfig calls GET /api/v1/public/widget-config: Pre-ticket config for the embeddable widget + hosted form (the branding footer renders before any ticket exists).
func (a *GeneratedAPI) PublicWidgetConfig(ctx context.Context, p *PublicWidgetConfigArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicWidgetConfigArgs{}
	}
	q := url.Values{}
	if p.Account != nil {
		q.Set("account", apigenQueryValue(p.Account))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/public/widget-config", q, nil)
}

// ReportsSummaryArgs are the inputs of GeneratedAPI.ReportsSummary.
type ReportsSummaryArgs struct {
	// Days is "days" in the query.
	Days any `query:"days"`
}

// ReportsSummary calls GET /api/v1/reports/summary: List summary.
func (a *GeneratedAPI) ReportsSummary(ctx context.Context, p *ReportsSummaryArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ReportsSummaryArgs{}
	}
	q := url.Values{}
	if p.Days != nil {
		q.Set("days", apigenQueryValue(p.Days))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/reports/summary", q, nil)
}

// RequesterCreateTicketsArgs are the inputs of GeneratedAPI.RequesterCreateTickets.
type RequesterCreateTicketsArgs struct {
	// Subject is "subject" in the body, required.
	Subject string `json:"subject"`

	// BodyField is "body" in the body, required.
	BodyField string `json:"body"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// RequesterCreateTickets calls POST /api/v1/requester/tickets: Create a ticket.
func (a *GeneratedAPI) RequesterCreateTickets(ctx context.Context, p *RequesterCreateTicketsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &RequesterCreateTicketsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Subject != "" {
		payload["subject"] = p.Subject
	}
	if p.BodyField != "" {
		payload["body"] = p.BodyField
	}
	if _, ok := payload["subject"]; !ok {
		return nil, apigenMissing("RequesterCreateTickets", "Subject")
	}
	if _, ok := payload["body"]; !ok {
		return nil, apigenMissing("RequesterCreateTickets", "BodyField")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/requester/tickets", nil, payload)
}

// RequesterMe calls GET /api/v1/requester/me: List me.
func (a *GeneratedAPI) RequesterMe(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/requester/me", nil, nil)
}

// RequesterTicketsArgs are the inputs of GeneratedAPI.RequesterTickets.
type RequesterTicketsArgs struct {
	// Status is "status" in the query. One of: open, resolved, all.
	Status *string `query:"status"`
}

// RequesterTickets calls GET /api/v1/requester/tickets: List tickets.
func (a *GeneratedAPI) RequesterTickets(ctx context.Context, p *RequesterTicketsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &RequesterTicketsArgs{}
	}
	q := url.Values{}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(*p.Status))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/requester/tickets", q, nil)
}

// RequesterTickets2 calls GET /api/v1/requester/tickets/{number}: Get a ticket.
func (a *GeneratedAPI) RequesterTickets2(ctx context.Context, number string) (json.RawMessage, error) {
	path := "/api/v1/requester/tickets/" + url.PathEscape(number)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// RequesterTicketsMessagesArgs are the inputs of GeneratedAPI.RequesterTicketsMessages.
type RequesterTicketsMessagesArgs struct {
	// BodyField is "body" in the body, required.
	BodyField string `json:"body"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// RequesterTicketsMessages calls POST /api/v1/requester/tickets/{number}/messages: Messages a ticket.
func (a *GeneratedAPI) RequesterTicketsMessages(ctx context.Context, number string, p *RequesterTicketsMessagesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &RequesterTicketsMessagesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.BodyField != "" {
		payload["body"] = p.BodyField
	}
	if _, ok := payload["body"]; !ok {
		return nil, apigenMissing("RequesterTicketsMessages", "BodyField")
	}
	path := "/api/v1/requester/tickets/" + url.PathEscape(number) + "/messages"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// SettingsAutomation calls GET /api/v1/settings/automation: List automation.
func (a *GeneratedAPI) SettingsAutomation(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/settings/automation", nil, nil)
}

// SettingsBranding calls GET /api/v1/settings/branding: List branding.
func (a *GeneratedAPI) SettingsBranding(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/settings/branding", nil, nil)
}

// SettingsCreateBrandingLogoArgs are the inputs of GeneratedAPI.SettingsCreateBrandingLogo.
type SettingsCreateBrandingLogoArgs struct {
	// Length is "length" in the body.
	Length any `json:"length,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// SettingsCreateBrandingLogo calls POST /api/v1/settings/branding/logo: Create a logo.
func (a *GeneratedAPI) SettingsCreateBrandingLogo(ctx context.Context, p *SettingsCreateBrandingLogoArgs) (json.RawMessage, error) {
	if p == nil {
		p = &SettingsCreateBrandingLogoArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Length != nil {
		payload["length"] = p.Length
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/settings/branding/logo", nil, payload)
}

// SettingsDeleteBrandingLogo calls DELETE /api/v1/settings/branding/logo: Delete logo.
func (a *GeneratedAPI) SettingsDeleteBrandingLogo(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "DELETE", "/api/v1/settings/branding/logo", nil, nil)
}

// SettingsHelp calls GET /api/v1/settings/help: List help.
func (a *GeneratedAPI) SettingsHelp(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/settings/help", nil, nil)
}

// SettingsSetAutomationArgs are the inputs of GeneratedAPI.SettingsSetAutomation.
type SettingsSetAutomationArgs struct {
	// BusinessHours is "businessHours" in the body.
	BusinessHours map[string]any `json:"businessHours,omitempty"`

	// AutoResponseEnabled is "autoResponseEnabled" in the body.
	AutoResponseEnabled *bool `json:"autoResponseEnabled,omitempty"`

	// AutoResponseInside is "autoResponseInside" in the body.
	AutoResponseInside *string `json:"autoResponseInside,omitempty"`

	// AutoResponseOutside is "autoResponseOutside" in the body.
	AutoResponseOutside *string `json:"autoResponseOutside,omitempty"`

	// HideBranding is "hideBranding" in the body.
	HideBranding *bool `json:"hideBranding,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// SettingsSetAutomation calls PUT /api/v1/settings/automation: Set automation.
func (a *GeneratedAPI) SettingsSetAutomation(ctx context.Context, p *SettingsSetAutomationArgs) (json.RawMessage, error) {
	if p == nil {
		p = &SettingsSetAutomationArgs{}
	}
	payload := apigenBody(p.Body)
	if p.BusinessHours != nil {
		payload["businessHours"] = p.BusinessHours
	}
	if p.AutoResponseEnabled != nil {
		payload["autoResponseEnabled"] = *p.AutoResponseEnabled
	}
	if p.AutoResponseInside != nil {
		payload["autoResponseInside"] = *p.AutoResponseInside
	}
	if p.AutoResponseOutside != nil {
		payload["autoResponseOutside"] = *p.AutoResponseOutside
	}
	if p.HideBranding != nil {
		payload["hideBranding"] = *p.HideBranding
	}
	return a.c.apigenRequest(ctx, "PUT", "/api/v1/settings/automation", nil, payload)
}

// SettingsSetBrandingArgs are the inputs of GeneratedAPI.SettingsSetBranding.
type SettingsSetBrandingArgs struct {
	// Slug is "slug" in the body.
	Slug *string `json:"slug,omitempty"`

	// BrandName is "brandName" in the body.
	BrandName *string `json:"brandName,omitempty"`

	// BrandLogoURL is "brandLogoUrl" in the body.
	BrandLogoURL *string `json:"brandLogoUrl,omitempty"`

	// AccentColor is "accentColor" in the body.
	AccentColor *string `json:"accentColor,omitempty"`

	// BrandColor is "brandColor" in the body.
	BrandColor *string `json:"brandColor,omitempty"`

	// WidgetTextColor is "widgetTextColor" in the body.
	WidgetTextColor *string `json:"widgetTextColor,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// SettingsSetBranding calls PUT /api/v1/settings/branding: Set branding.
func (a *GeneratedAPI) SettingsSetBranding(ctx context.Context, p *SettingsSetBrandingArgs) (json.RawMessage, error) {
	if p == nil {
		p = &SettingsSetBrandingArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Slug != nil {
		payload["slug"] = *p.Slug
	}
	if p.BrandName != nil {
		payload["brandName"] = *p.BrandName
	}
	if p.BrandLogoURL != nil {
		payload["brandLogoUrl"] = *p.BrandLogoURL
	}
	if p.AccentColor != nil {
		payload["accentColor"] = *p.AccentColor
	}
	if p.BrandColor != nil {
		payload["brandColor"] = *p.BrandColor
	}
	if p.WidgetTextColor != nil {
		payload["widgetTextColor"] = *p.WidgetTextColor
	}
	return a.c.apigenRequest(ctx, "PUT", "/api/v1/settings/branding", nil, payload)
}

// SettingsSetHelpArgs are the inputs of GeneratedAPI.SettingsSetHelp.
type SettingsSetHelpArgs struct {
	// ContactEmail is "contactEmail" in the body.
	ContactEmail *string `json:"contactEmail,omitempty"`

	// ContactPhone is "contactPhone" in the body.
	ContactPhone *string `json:"contactPhone,omitempty"`

	// ContactAddress is "contactAddress" in the body.
	ContactAddress *string `json:"contactAddress,omitempty"`

	// DocsURL is "docsUrl" in the body.
	DocsURL *string `json:"docsUrl,omitempty"`

	// ContactURL is "contactUrl" in the body.
	ContactURL *string `json:"contactUrl,omitempty"`

	// HelpIntro is "helpIntro" in the body.
	HelpIntro *string `json:"helpIntro,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// SettingsSetHelp calls PUT /api/v1/settings/help: Set help.
func (a *GeneratedAPI) SettingsSetHelp(ctx context.Context, p *SettingsSetHelpArgs) (json.RawMessage, error) {
	if p == nil {
		p = &SettingsSetHelpArgs{}
	}
	payload := apigenBody(p.Body)
	if p.ContactEmail != nil {
		payload["contactEmail"] = *p.ContactEmail
	}
	if p.ContactPhone != nil {
		payload["contactPhone"] = *p.ContactPhone
	}
	if p.ContactAddress != nil {
		payload["contactAddress"] = *p.ContactAddress
	}
	if p.DocsURL != nil {
		payload["docsUrl"] = *p.DocsURL
	}
	if p.ContactURL != nil {
		payload["contactUrl"] = *p.ContactURL
	}
	if p.HelpIntro != nil {
		payload["helpIntro"] = *p.HelpIntro
	}
	return a.c.apigenRequest(ctx, "PUT", "/api/v1/settings/help", nil, payload)
}

// TicketsCreateArgs are the inputs of GeneratedAPI.TicketsCreate.
type TicketsCreateArgs struct {
	// Subject is "subject" in the body, required.
	Subject string `json:"subject"`

	// BodyField is "body" in the body, required.
	BodyField string `json:"body"`

	// RequesterEmail is "requesterEmail" in the body, required.
	RequesterEmail string `json:"requesterEmail"`

	// RequesterName is "requesterName" in the body.
	RequesterName *string `json:"requesterName,omitempty"`

	// Priority is "priority" in the body.
	Priority *string `json:"priority,omitempty"`

	// Channel is "channel" in the body. One of: web, email, whatsapp.
	Channel *string `json:"channel,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// TicketsCreate calls POST /api/v1/tickets: Agent-created ticket (logging an inquiry that arrived out-of-band, e.g.
func (a *GeneratedAPI) TicketsCreate(ctx context.Context, p *TicketsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &TicketsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Subject != "" {
		payload["subject"] = p.Subject
	}
	if p.BodyField != "" {
		payload["body"] = p.BodyField
	}
	if p.RequesterEmail != "" {
		payload["requesterEmail"] = p.RequesterEmail
	}
	if p.RequesterName != nil {
		payload["requesterName"] = *p.RequesterName
	}
	if p.Priority != nil {
		payload["priority"] = *p.Priority
	}
	if p.Channel != nil {
		payload["channel"] = *p.Channel
	}
	if _, ok := payload["subject"]; !ok {
		return nil, apigenMissing("TicketsCreate", "Subject")
	}
	if _, ok := payload["body"]; !ok {
		return nil, apigenMissing("TicketsCreate", "BodyField")
	}
	if _, ok := payload["requesterEmail"]; !ok {
		return nil, apigenMissing("TicketsCreate", "RequesterEmail")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/tickets", nil, payload)
}

// TicketsGet calls GET /api/v1/tickets/{id}: Get a ticket.
func (a *GeneratedAPI) TicketsGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/tickets/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// TicketsListArgs are the inputs of GeneratedAPI.TicketsList.
type TicketsListArgs struct {
	// Status is "status" in the query. One of: open, pending, resolved, closed, all.
	Status *string `query:"status"`

	// Assignee is "assignee" in the query.
	Assignee *string `query:"assignee"`

	// Tag is "tag" in the query.
	Tag *string `query:"tag"`

	// Channel is "channel" in the query. One of: web, email, whatsapp, telegram.
	Channel *string `query:"channel"`

	// Priority is "priority" in the query. One of: low, normal, high, urgent.
	Priority *string `query:"priority"`

	// Q is "q" in the query.
	Q *string `query:"q"`

	// Limit is "limit" in the query.
	Limit *int `query:"limit"`

	// Cursor is "cursor" in the query.
	Cursor *string `query:"cursor"`
}

// TicketsList calls GET /api/v1/tickets: List tickets.
func (a *GeneratedAPI) TicketsList(ctx context.Context, p *TicketsListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &TicketsListArgs{}
	}
	q := url.Values{}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(*p.Status))
	}
	if p.Assignee != nil {
		q.Set("assignee", apigenQueryValue(*p.Assignee))
	}
	if p.Tag != nil {
		q.Set("tag", apigenQueryValue(*p.Tag))
	}
	if p.Channel != nil {
		q.Set("channel", apigenQueryValue(*p.Channel))
	}
	if p.Priority != nil {
		q.Set("priority", apigenQueryValue(*p.Priority))
	}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(*p.Q))
	}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(*p.Limit))
	}
	if p.Cursor != nil {
		q.Set("cursor", apigenQueryValue(*p.Cursor))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/tickets", q, nil)
}

// TicketsMessagesArgs are the inputs of GeneratedAPI.TicketsMessages.
type TicketsMessagesArgs struct {
	// BodyField is "body" in the body, required.
	BodyField string `json:"body"`

	// IsInternal is "isInternal" in the body.
	IsInternal *bool `json:"isInternal,omitempty"`

	// AuthorName is "authorName" in the body.
	AuthorName *string `json:"authorName,omitempty"`

	// AttachmentIDs is "attachmentIds" in the body.
	AttachmentIDs []string `json:"attachmentIds,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// TicketsMessages calls POST /api/v1/tickets/{id}/messages: Messages a ticket.
func (a *GeneratedAPI) TicketsMessages(ctx context.Context, id string, p *TicketsMessagesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &TicketsMessagesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.BodyField != "" {
		payload["body"] = p.BodyField
	}
	if p.IsInternal != nil {
		payload["isInternal"] = *p.IsInternal
	}
	if p.AuthorName != nil {
		payload["authorName"] = *p.AuthorName
	}
	if p.AttachmentIDs != nil {
		payload["attachmentIds"] = p.AttachmentIDs
	}
	if _, ok := payload["body"]; !ok {
		return nil, apigenMissing("TicketsMessages", "BodyField")
	}
	path := "/api/v1/tickets/" + url.PathEscape(id) + "/messages"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// TicketsTags calls GET /api/v1/tickets/tags: Distinct tags across the workspace's tickets — autocomplete feed. (Must be mounted before /:id so 'tags' isn't read as a ticket id.).
func (a *GeneratedAPI) TicketsTags(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/tickets/tags", nil, nil)
}

// TicketsUpdateArgs are the inputs of GeneratedAPI.TicketsUpdate.
type TicketsUpdateArgs struct {
	// Status is "status" in the body.
	Status *string `json:"status,omitempty"`

	// Priority is "priority" in the body.
	Priority *string `json:"priority,omitempty"`

	// AssigneeSub is "assigneeSub" in the body.
	AssigneeSub *string `json:"assigneeSub,omitempty"`

	// Tags is "tags" in the body.
	Tags []string `json:"tags,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// TicketsUpdate calls PATCH /api/v1/tickets/{id}: Update a ticket.
func (a *GeneratedAPI) TicketsUpdate(ctx context.Context, id string, p *TicketsUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &TicketsUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Status != nil {
		payload["status"] = *p.Status
	}
	if p.Priority != nil {
		payload["priority"] = *p.Priority
	}
	if p.AssigneeSub != nil {
		payload["assigneeSub"] = *p.AssigneeSub
	}
	if p.Tags != nil {
		payload["tags"] = p.Tags
	}
	path := "/api/v1/tickets/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// WebhookSubscriptionsCreateArgs are the inputs of GeneratedAPI.WebhookSubscriptionsCreate.
type WebhookSubscriptionsCreateArgs struct {
	// URL is "url" in the body, required.
	URL string `json:"url"`

	// Events is "events" in the body.
	Events []string `json:"events,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// WebhookSubscriptionsCreate calls POST /api/v1/webhook-subscriptions: Create a webhook subscription.
func (a *GeneratedAPI) WebhookSubscriptionsCreate(ctx context.Context, p *WebhookSubscriptionsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WebhookSubscriptionsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.URL != "" {
		payload["url"] = p.URL
	}
	if p.Events != nil {
		payload["events"] = p.Events
	}
	if _, ok := payload["url"]; !ok {
		return nil, apigenMissing("WebhookSubscriptionsCreate", "URL")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/webhook-subscriptions", nil, payload)
}

// WebhookSubscriptionsDelete calls DELETE /api/v1/webhook-subscriptions/{id}: Delete a webhook subscription.
func (a *GeneratedAPI) WebhookSubscriptionsDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/webhook-subscriptions/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// WebhookSubscriptionsList calls GET /api/v1/webhook-subscriptions: List webhook subscriptions.
func (a *GeneratedAPI) WebhookSubscriptionsList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/webhook-subscriptions", nil, nil)
}

// WebhookSubscriptionsUpdateArgs are the inputs of GeneratedAPI.WebhookSubscriptionsUpdate.
type WebhookSubscriptionsUpdateArgs struct {
	// Active is "active" in the body, required.
	Active bool `json:"active"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// WebhookSubscriptionsUpdate calls PATCH /api/v1/webhook-subscriptions/{id}: Update a webhook subscription.
func (a *GeneratedAPI) WebhookSubscriptionsUpdate(ctx context.Context, id string, p *WebhookSubscriptionsUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WebhookSubscriptionsUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if _, ok := payload["active"]; !ok || p.Active {
		payload["active"] = p.Active
	}
	path := "/api/v1/webhook-subscriptions/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// apigenBody copies Body, so the fields set over it never change the caller's map.
func apigenBody(body map[string]any) map[string]any {
	out := make(map[string]any, len(body))
	for k, v := range body {
		out[k] = v
	}
	return out
}

// apigenQueryValue writes a query value the way the server reads it: strings as they are,
// numbers and booleans as JSON writes them, anything else as JSON.
func apigenQueryValue(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		return strconv.FormatBool(x)
	case int:
		return strconv.Itoa(x)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	}
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprint(v)
	}
	return string(b)
}

// apigenMissing is the error for a required body field that was neither set nor in Body.
func apigenMissing(method, field string) error {
	return fmt.Errorf("%s needs %s (or its key in Body)", method, field)
}
